services:
  giveflow_db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"

  giveflow_api:
    build: .
    environment:
      DATABASE_URL: postgresql://user:password@giveflow_db:5432/dbname
    depends_on:
      - giveflow_db
    ports:
      - "8000:8000"
